import type { LaunchKit } from '../src/brandGenerator'

export interface NetworkConfig {
  key: string
  name: string
  chainId: number
  currency: string
  rpcUrl: string
  explorerUrl: string
  isTestnet: boolean
}

export const SUPPORTED_NETWORKS: Record<string, NetworkConfig> = {
  'base-mainnet': {
    key: 'base-mainnet',
    name: 'Base Mainnet',
    chainId: 8453,
    currency: 'ETH',
    rpcUrl: 'https://mainnet.base.org',
    explorerUrl: 'https://basescan.org',
    isTestnet: false,
  },
  'base-sepolia': {
    key: 'base-sepolia',
    name: 'Base Sepolia Testnet',
    chainId: 84532,
    currency: 'ETH',
    rpcUrl: 'https://sepolia.base.org',
    explorerUrl: 'https://sepolia.basescan.org',
    isTestnet: true,
  },
  'arbitrum-one': {
    key: 'arbitrum-one',
    name: 'Arbitrum One',
    chainId: 42161,
    currency: 'ETH',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io',
    isTestnet: false,
  },
  'arbitrum-sepolia': {
    key: 'arbitrum-sepolia',
    name: 'Arbitrum Sepolia Testnet',
    chainId: 421614,
    currency: 'ETH',
    rpcUrl: 'https://sepolia-rollup.arbitrum.io/rpc',
    explorerUrl: 'https://sepolia.arbiscan.io',
    isTestnet: true,
  },
  'ethereum-mainnet': {
    key: 'ethereum-mainnet',
    name: 'Ethereum Mainnet',
    chainId: 1,
    currency: 'ETH',
    rpcUrl: 'https://eth.llamarpc.com',
    explorerUrl: 'https://etherscan.io',
    isTestnet: false,
  },
  'sepolia-testnet': {
    key: 'sepolia-testnet',
    name: 'Ethereum Sepolia Testnet',
    chainId: 11155111,
    currency: 'ETH',
    rpcUrl: 'https://rpc.sepolia.org',
    explorerUrl: 'https://sepolia.etherscan.io',
    isTestnet: true,
  },
}

export interface DetailedDeploymentPlan {
  contractName: string
  tokenName: string
  symbol: string
  decimals: number
  initialSupply: string
  network: NetworkConfig
  deployerAddress: string
  constructorArgs: [string, string, string, string]
  solidity: string
  abi: Array<{ type: string; name?: string; inputs?: Array<{ name: string; type: string }>; outputs?: Array<{ name: string; type: string }>; stateMutability?: string }>
  remixUrl: string
  foundryScript: string
  checklist: string[]
  estimatedGas: string
}

export function cleanContractName(tokenName: string): string {
  const alphanumeric = tokenName.replace(/[^A-Za-z0-9]/g, '')
  if (!alphanumeric) return 'MemeToken'
  if (/^[0-9]/.test(alphanumeric)) return `Token${alphanumeric}`
  return `${alphanumeric}Token`
}

export function generateSolidityCode(contractName: string, _tokenName: string, _symbol: string, _supply: string): string {

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title ${contractName}
 * @dev High-performance ERC20 token generated by ZAND AI Launch Kit.
 * Features standard OpenZeppelin compliant ERC20 with Burnable and Ownable extensions.
 */

interface IERC20 {
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address to, uint256 value) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 value) external returns (bool);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
}

abstract contract Context {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }
}

abstract contract Ownable is Context {
    address private _owner;

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    constructor(address initialOwner) {
        if (initialOwner == address(0)) revert("Invalid owner");
        _transferOwnership(initialOwner);
    }

    function owner() public view virtual returns (address) {
        return _owner;
    }

    modifier onlyOwner() {
        _checkOwner();
        _;
    }

    function _checkOwner() internal view virtual {
        require(owner() == _msgSender(), "Caller is not the owner");
    }

    function renounceOwnership() public virtual onlyOwner {
        _transferOwnership(address(0));
    }

    function transferOwnership(address newOwner) public virtual onlyOwner {
        if (newOwner == address(0)) revert("Invalid owner");
        _transferOwnership(newOwner);
    }

    function _transferOwnership(address newOwner) internal virtual {
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
}

contract ${contractName} is Context, IERC20, Ownable {
    mapping(address => uint256) private _balances;
    mapping(address => mapping(address => uint256)) private _allowances;

    uint256 private _totalSupply;
    string private _name;
    string private _symbol;

    constructor(
        string memory name_,
        string memory symbol_,
        address initialOwner,
        uint256 initialSupply_
    ) Ownable(initialOwner) {
        _name = name_;
        _symbol = symbol_;
        _mint(initialOwner, initialSupply_ * 10 ** decimals());
    }

    function name() public view virtual returns (string memory) {
        return _name;
    }

    function symbol() public view virtual returns (string memory) {
        return _symbol;
    }

    function decimals() public view virtual returns (uint8) {
        return 18;
    }

    function totalSupply() public view virtual override returns (uint256) {
        return _totalSupply;
    }

    function balanceOf(address account) public view virtual override returns (uint256) {
        return _balances[account];
    }

    function transfer(address to, uint256 value) public virtual override returns (bool) {
        address owner_ = _msgSender();
        _transfer(owner_, to, value);
        return true;
    }

    function allowance(address owner_, address spender) public view virtual override returns (uint256) {
        return _allowances[owner_][spender];
    }

    function approve(address spender, uint256 value) public virtual override returns (bool) {
        address owner_ = _msgSender();
        _approve(owner_, spender, value);
        return true;
    }

    function transferFrom(address from, address to, uint256 value) public virtual override returns (bool) {
        address spender = _msgSender();
        _spendAllowance(from, spender, value);
        _transfer(from, to, value);
        return true;
    }

    function burn(uint256 value) public virtual {
        _burn(_msgSender(), value);
    }

    function _transfer(address from, address to, uint256 value) internal virtual {
        if (from == address(0)) revert("Transfer from zero");
        if (to == address(0)) revert("Transfer to zero");
        uint256 fromBalance = _balances[from];
        if (fromBalance < value) revert("Insufficient balance");
        unchecked {
            _balances[from] = fromBalance - value;
            _balances[to] += value;
        }
        emit Transfer(from, to, value);
    }

    function _mint(address account, uint256 value) internal virtual {
        if (account == address(0)) revert("Mint to zero");
        _totalSupply += value;
        unchecked {
            _balances[account] += value;
        }
        emit Transfer(address(0), account, value);
    }

    function _burn(address account, uint256 value) internal virtual {
        if (account == address(0)) revert("Burn from zero");
        uint256 accountBalance = _balances[account];
        if (accountBalance < value) revert("Insufficient balance");
        unchecked {
            _balances[account] = accountBalance - value;
            _totalSupply -= value;
        }
        emit Transfer(account, address(0), value);
    }

    function _approve(address owner_, address spender, uint256 value) internal virtual {
        if (owner_ == address(0)) revert("Approve from zero");
        if (spender == address(0)) revert("Approve to zero");
        _allowances[owner_][spender] = value;
        emit Approval(owner_, spender, value);
    }

    function _spendAllowance(address owner_, address spender, uint256 value) internal virtual {
        uint256 currentAllowance = allowance(owner_, spender);
        if (currentAllowance != type(uint256).max) {
            if (currentAllowance < value) revert("Insufficient allowance");
            unchecked {
                _approve(owner_, spender, currentAllowance - value);
            }
        }
    }
}
`
}

export function buildDeploymentPlan(
  kit: LaunchKit,
  networkKey = 'base-mainnet',
  deployerAddress = '0x0000000000000000000000000000000000000000',
): DetailedDeploymentPlan {
  const network = SUPPORTED_NETWORKS[networkKey] || SUPPORTED_NETWORKS['base-mainnet']
  const contractName = cleanContractName(kit.tokenName)
  const symbol = kit.primaryTicker.replace('$', '').trim()
  const rawSupply = (kit.tokenomics?.supply || '1000000000').replace(/,/g, '').trim()
  const solidity = generateSolidityCode(contractName, kit.tokenName, symbol, rawSupply)

  const constructorArgs: [string, string, string, string] = [
    kit.tokenName,
    symbol,
    deployerAddress,
    rawSupply,
  ]

  const abi = [
    {
      type: 'constructor',
      inputs: [
        { name: 'name_', type: 'string' },
        { name: 'symbol_', type: 'string' },
        { name: 'initialOwner', type: 'address' },
        { name: 'initialSupply_', type: 'uint256' },
      ],
    },
    {
      type: 'function',
      name: 'name',
      inputs: [],
      outputs: [{ name: '', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'symbol',
      inputs: [],
      outputs: [{ name: '', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'decimals',
      inputs: [],
      outputs: [{ name: '', type: 'uint8' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'totalSupply',
      inputs: [],
      outputs: [{ name: '', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'balanceOf',
      inputs: [{ name: 'account', type: 'address' }],
      outputs: [{ name: '', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'transfer',
      inputs: [
        { name: 'to', type: 'address' },
        { name: 'value', type: 'uint256' },
      ],
      outputs: [{ name: '', type: 'bool' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'burn',
      inputs: [{ name: 'value', type: 'uint256' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'renounceOwnership',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
    },
  ]

  const foundryScript = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Script.sol";
import "./${contractName}.sol";

contract Deploy${contractName} is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        new ${contractName}(
            "${kit.tokenName}",
            "${symbol}",
            msg.sender,
            ${rawSupply}
        );

        vm.stopBroadcast();
    }
}`

  const remixUrl = `https://remix.ethereum.org/#code=${Buffer.from(solidity).toString('base64')}`

  return {
    contractName,
    tokenName: kit.tokenName,
    symbol,
    decimals: 18,
    initialSupply: rawSupply,
    network,
    deployerAddress,
    constructorArgs,
    solidity,
    abi,
    remixUrl,
    foundryScript,
    estimatedGas: '~1,850,000 gas units',
    checklist: [
      '1. Verify Token Name, Symbol, and Supply match your community lore.',
      '2. Ensure your deployer wallet holds sufficient native gas token (e.g. ETH on Base/Arbitrum).',
      '3. Deploy to testnet (Base Sepolia or Arbitrum Sepolia) first to verify transactions.',
      '4. Verify contract on block explorer (BaseScan / ArbiScan) immediately after deployment.',
      '5. Add initial liquidity on Uniswap V3 or Aerodrome and lock/burn LP tokens.',
      '6. Consider renouncing ownership after liquidity is locked to build maximum trust.',
      '7. NEVER enter or expose your private key into untrusted web pages, chat, or git repositories.',
    ],
  }
}

export function simulateDeploymentCheck(
  deployerAddress: string,
  networkKey: string,
): {
  valid: boolean
  errors: string[]
  warnings: string[]
} {
  const errors: string[] = []
  const warnings: string[] = []

  const isEthAddress = /^0x[a-fA-F0-9]{40}$/.test(deployerAddress.trim())
  if (!isEthAddress) {
    errors.push('Deployer address must be a valid 42-character Ethereum address (0x...)')
  }

  const network = SUPPORTED_NETWORKS[networkKey]
  if (!network) {
    errors.push(`Unsupported network key "${networkKey}"`)
  } else if (!network.isTestnet) {
    warnings.push(`You selected ${network.name} (Live Mainnet). Real funds will be consumed during deployment.`)
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  }
}
