import type { LaunchKit } from '../src/brandGenerator'

export interface TelegramBotPackage {
  filename: string
  code: string
  botPackageJson: string
  readme: string
  slashCommands: { command: string; description: string; sampleResponse: string }[]
}

export function generateTelegramBotPackage(
  kit: LaunchKit,
  options: {
    ethereumAddress?: string
    baseAddress?: string
    solanaMint?: string
  } = {},
): TelegramBotPackage {
  const symbol = kit.primaryTicker
  const baseContract = options.baseAddress || '0x_BASE_CONTRACT_ADDRESS_HERE'
  const ethContract = options.ethereumAddress || '0x_ETH_CONTRACT_ADDRESS_HERE'
  const solContract = options.solanaMint || 'SOL_MINT_ADDRESS_HERE'

  const slashCommands = [
    {
      command: '/start',
      description: `Welcome & launch dashboard for ${kit.tokenName}`,
      sampleResponse: `🔥 Welcome to the official ${kit.tokenName} (${symbol}) community! Describe a meme. AI builds the brand.\n\nUse /buy, /lore, /memes, or /raid to get started!`,
    },
    {
      command: '/lore',
      description: `Origin story and ${kit.character.name} lore`,
      sampleResponse: `${kit.lore}\n\nCatchphrase: "${kit.character.catchphrase}"`,
    },
    {
      command: '/buy',
      description: 'Multi-chain buy links (Uniswap, Raydium, Robinhood)',
      sampleResponse: `🛒 How to buy ${symbol}:\n\n• Base (Aerodrome/Uniswap): https://app.uniswap.org/swap?chain=base&outputCurrency=${baseContract}\n• Ethereum (Uniswap): https://app.uniswap.org/swap?chain=ethereum&outputCurrency=${ethContract}\n• Solana (Raydium): https://raydium.io/swap/?outputCurrency=${solContract}\n• Robinhood Connect: Onramp fiat directly with zero fees`,
    },
    {
      command: '/contract',
      description: 'Verified smart contract addresses',
      sampleResponse: `📜 ${kit.tokenName} Verified Contracts:\n\n• Base: \`${baseContract}\`\n• Ethereum: \`${ethContract}\`\n• Solana: \`${solContract}\``,
    },
    {
      command: '/memes',
      description: 'Get a fresh generated meme template',
      sampleResponse: `😾 Meme: "${kit.memeTemplates[0]?.top || 'BUY THE DIP'}" / "${kit.memeTemplates[0]?.bottom || 'PAPER HANDS ROASTED'}"`,
    },
    {
      command: '/raid',
      description: 'Twitter / X community raid target and copy',
      sampleResponse: `⚔️ RAID ALERT! Copy this tweet and reply to Wall Street:\n\n"${kit.socialPosts[0] || 'The raid is on!'}"\n\n$CLAW #Base #Solana #Robinhood`,
    },
    {
      command: '/tokenomics',
      description: 'Tokenomics and supply breakdown',
      sampleResponse: `📊 ${kit.tokenName} Tokenomics:\n\n• Total Supply: ${kit.tokenomics.supply}\n• Tax: ${kit.tokenomics.tax}\n• Liquidity: ${kit.tokenomics.liquidity}\n• Chain: ${kit.tokenomics.chain}`,
    },
    {
      command: '/chart',
      description: 'Live price chart and DEXScreener links',
      sampleResponse: `📈 DEXScreener: https://dexscreener.com/base/${baseContract}\nBirdeye: https://birdeye.so/token/${solContract}`,
    },
  ]

  const botCode = `/**
 * Official Telegram Community Bot for ${kit.tokenName} (${symbol})
 * Generated by ZAND AI Launch Kit.
 * Run with: npm install && npm start
 */

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
if (!BOT_TOKEN) {
  console.error("Error: TELEGRAM_BOT_TOKEN environment variable is required.");
  process.exit(1);
}

const BASE_CONTRACT = process.env.BASE_CONTRACT || "${baseContract}";
const ETH_CONTRACT = process.env.ETH_CONTRACT || "${ethContract}";
const SOL_MINT = process.env.SOL_MINT || "${solContract}";

async function telegramRequest(method, body) {
  const url = \`https://api.telegram.org/bot\${BOT_TOKEN}/\${method}\`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  return res.json();
}

async function handleMessage(message) {
  const chatId = message.chat.id;
  const text = (message.text || "").trim();

  if (text.startsWith("/start")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`🚀 *Welcome to the official ${kit.tokenName} (${symbol}) Community!*\\n\\n*Mascot:* ${kit.character.name} (${kit.character.archetype})\\n*Catchphrase:* "${kit.character.catchphrase}"\\n\\n*Commands:*\\n/buy - Swap links (Base, Ethereum, Solana)\\n/lore - Origin story & manifesto\\n/memes - Fresh meme templates\\n/raid - Twitter/X raid templates\\n/contract - Official verified contract addresses\\n/tokenomics - Tokenomics & lock status\\n/chart - Live DEXScreener chart\`,
      parse_mode: "Markdown",
    });
  }

  if (text.startsWith("/buy")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`🛒 *Buy ${symbol} across major chains:*\\n\\n🔷 *Base Mainnet:*\\nhttps://app.uniswap.org/swap?chain=base&outputCurrency=\${BASE_CONTRACT}\\n\\n💎 *Ethereum Mainnet:*\\nhttps://app.uniswap.org/swap?chain=ethereum&outputCurrency=\${ETH_CONTRACT}\\n\\n🟣 *Solana (Raydium):*\\nhttps://raydium.io/swap/?outputCurrency=\${SOL_MINT}\\n\\n💳 *Robinhood Connect:*\\nAvailable on our official website\`,
      parse_mode: "Markdown",
    });
  }

  if (text.startsWith("/lore")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`📜 *The Legend of ${kit.tokenName}:*\\n\\n${kit.lore.replace(/[*_`]/g, "")}\\n\\n*"${kit.character.catchphrase}"*\`,
      parse_mode: "Markdown",
    });
  }

  if (text.startsWith("/contract")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`📜 *Official Contract Addresses for ${symbol}:*\\n\\n• *Base:* \`\${BASE_CONTRACT}\`\\n• *Ethereum:* \`\${ETH_CONTRACT}\`\\n• *Solana:* \`\${SOL_MINT}\`\\n\\n⚠️ *Always verify before swapping! Never trust direct DMs.*\` ,
      parse_mode: "Markdown",
    });
  }

  if (text.startsWith("/memes")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`😾 *${kit.tokenName} Meme Studio:*\\n\\n"${kit.memeTemplates[0]?.top || 'HODL'}"\\n\\n[ Mascot: ${kit.character.name} ]\\n\\n"${kit.memeTemplates[0]?.bottom || 'TO THE MOON'}"\`,
      parse_mode: "Markdown",
    });
  }

  if (text.startsWith("/raid")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`⚔️ *COMMUNITY RAID IN PROGRESS!*\\n\\nCopy and post this to X/Twitter:\\n\\n"${kit.socialPosts[0]}"\\n\\n#${symbol.replace('$', '')} #Base #Solana #Ethereum #Robinhood\`,
      parse_mode: "Markdown",
    });
  }

  if (text.startsWith("/tokenomics")) {
    return telegramRequest("sendMessage", {
      chat_id: chatId,
      text: \`📊 *${symbol} Tokenomics Blueprint:*\\n\\n• *Total Supply:* ${kit.tokenomics.supply}\\n• *Tax:* ${kit.tokenomics.tax}\\n• *Liquidity:* ${kit.tokenomics.liquidity}\\n• *Chain:* ${kit.tokenomics.chain}\`,
      parse_mode: "Markdown",
    });
  }
}

async function pollUpdates(offset = 0) {
  try {
    const res = await telegramRequest("getUpdates", { offset, timeout: 30 });
    if (res.ok && Array.isArray(res.result)) {
      for (const update of res.result) {
        if (update.message) {
          await handleMessage(update.message);
        }
        offset = update.update_id + 1;
      }
    }
  } catch (err) {
    console.error("Polling error:", err);
  }
  setTimeout(() => pollUpdates(offset), 1000);
}

console.log("⚡ ${kit.tokenName} Telegram Community Bot started polling...");
pollUpdates();
`

  const botPackageJson = JSON.stringify(
    {
      name: `${symbol.replace('$', '').toLowerCase()}-telegram-bot`,
      version: '1.0.0',
      description: `Official Telegram Community Bot for ${kit.tokenName}`,
      main: 'bot.js',
      scripts: {
        start: 'node bot.js',
      },
      dependencies: {},
    },
    null,
    2,
  )

  const readme = `# ${kit.tokenName} (${symbol}) Community Telegram Bot

### Quick Start
1. Create a bot and obtain your token from [@BotFather](https://t.me/BotFather).
2. Set your environment variable:
   \`\`\`bash
   export TELEGRAM_BOT_TOKEN="your-bot-token-here"
   export BASE_CONTRACT="${baseContract}"
   export ETH_CONTRACT="${ethContract}"
   export SOL_MINT="${solContract}"
   \`\`\`
3. Start the bot:
   \`\`\`bash
   npm start
   \`\`\`
`

  return {
    filename: 'bot.js',
    code: botCode,
    botPackageJson,
    readme,
    slashCommands,
  }
}
