import JSZip from 'jszip'
import { exportLaunchKitMarkdown, type LaunchKit } from './brandGenerator'
import { generateLandingPageHtml } from './landingPage'
import { generateVerificationPackage } from './verification'
import { DEFAULT_ALLOCATIONS, generateVestingSolidityContract } from './vesting'
import { generateListingPackage } from './listingKit'

import { generateLocalizedManifestos } from './localization'

export interface RaidKitFileStructure {
  kit: LaunchKit
  logoSvg?: string
  bannerSvg?: string
  solidityCode?: string
  baseContractAddress?: string
  ethereumContractAddress?: string
  solanaMintAddress?: string
  robinhoodContractAddress?: string
}

export async function generateRaidKitZip(data: RaidKitFileStructure): Promise<Blob> {
  const zip = new JSZip()
  const kit = data.kit
  const symbol = kit.primaryTicker
  const cleanSymbol = symbol.replace('$', '').toLowerCase()

  const activeContract =
    data.robinhoodContractAddress ||
    data.baseContractAddress ||
    data.ethereumContractAddress ||
    '0x42170bA5E8C9472DaE419Fa432170DEAdbeef123'

  // 1. Root Documentation
  zip.file(
    'README.md',
    `# ${kit.tokenName} (${symbol}) — Official Launch & Raid Kit

Generated by ZAND AI Platform.

## Contents
- \`landing/\` — Standalone responsive HTML5 website (1-click deploy to Vercel/Netlify)
- \`MANIFESTO.md\` — Complete lore, narrative, and website copy
- \`TOKENOMICS.json\` — Supply, tax, and liquidity lock specifications
- \`TOKENOMICS_VESTING.json\` — Complete multi-sig and vesting schedule allocation table
- \`TWEETS.txt\` — Viral launch tweet storms and community raid scripts
- \`assets/\` — High-resolution 1:1 Logo and 3:1 Social Header Banner
- \`contracts/\` — Solidity ERC20 contracts for Robinhood/Base/Ethereum, TokenVesting.sol, and Block Explorer verification standard JSON
- \`bot/\` — Ready-to-deploy Telegram community bot
- \`exchanges/\` — Uniswap/Raydium liquidity guides, Robinhood audit, and DexScreener/CoinGecko listing applications
`,
  )

  // Landing Page Folder
  const landingFolder = zip.folder('landing')
  if (landingFolder) {
    const landingHtml = generateLandingPageHtml(kit, {
      contractAddress: activeContract,
      networkName: data.robinhoodContractAddress
        ? 'Robinhood Chain Mainnet (42170)'
        : data.baseContractAddress
          ? 'Base Mainnet'
          : 'Multi-Chain',
    })
    landingFolder.file('index.html', landingHtml)
  }

  zip.file('MANIFESTO.md', exportLaunchKitMarkdown(kit))

  // Multi-Language Manifestos Folder
  const manifestosFolder = zip.folder('manifestos')
  if (manifestosFolder) {
    const localized = generateLocalizedManifestos(kit)
    manifestosFolder.file('MANIFESTO_EN.md', localized.en.markdown)
    manifestosFolder.file('MANIFESTO_ZH.md', localized.zh.markdown)
    manifestosFolder.file('MANIFESTO_KR.md', localized.kr.markdown)
    manifestosFolder.file('MANIFESTO_JP.md', localized.jp.markdown)
    manifestosFolder.file('MANIFESTO_ES.md', localized.es.markdown)
  }

  zip.file(
    'TOKENOMICS.json',
    JSON.stringify(
      {
        tokenName: kit.tokenName,
        ticker: kit.primaryTicker,
        tokenomics: kit.tokenomics,
        chains: ['Robinhood Mainnet', 'Base', 'Ethereum', 'Solana'],
        generatedAt: new Date().toISOString(),
      },
      null,
      2,
    ),
  )

  zip.file(
    'TOKENOMICS_VESTING.json',
    JSON.stringify(
      {
        tokenName: kit.tokenName,
        ticker: kit.primaryTicker,
        allocations: DEFAULT_ALLOCATIONS,
        generatedAt: new Date().toISOString(),
      },
      null,
      2,
    ),
  )

  // 2. Twitter / X Launch Storm
  const tweetsText = `=== OFFICIAL LAUNCH TWEET STORM ===\n\n` +
    kit.socialPosts.map((post, i) => `[Tweet ${i + 1}]\n${post}\n\n`).join('') +
    `\n=== RAID MESSAGES ===\n` +
    `1. $${cleanSymbol.toUpperCase()} is taking over. Describe a meme, AI builds the brand.\n` +
    `2. No presale, 0% tax, 100% community. Raid with us!\n` +
    `3. Verified on Robinhood Chain, Base, Ethereum, and Solana. #MemeSeason #${cleanSymbol.toUpperCase()}\n`
  zip.file('TWEETS.txt', tweetsText)

  // 3. Assets Folder
  const assetsFolder = zip.folder('assets')
  if (assetsFolder) {
    if (data.logoSvg) {
      assetsFolder.file('logo.svg', data.logoSvg)
    }
    if (data.bannerSvg) {
      assetsFolder.file('banner.svg', data.bannerSvg)
    }
    assetsFolder.file(
      'memes.json',
      JSON.stringify(
        {
          mascot: kit.character,
          templates: kit.memeTemplates,
        },
        null,
        2,
      ),
    )
  }

  // 4. Contracts Folder (Robinhood, Ethereum, Solana, Vesting & Verification)
  const contractsFolder = zip.folder('contracts')
  if (contractsFolder) {
    const ethFolder = contractsFolder.folder('ethereum')
    if (ethFolder && data.solidityCode) {
      ethFolder.file(`${kit.tokenName.replace(/[^A-Za-z0-9]/g, '') || 'Token'}.sol`, data.solidityCode)
    }

    contractsFolder.file('TokenVesting.sol', generateVestingSolidityContract(kit))

    // Verification package
    const verFolder = contractsFolder.folder('verification')
    if (verFolder) {
      const verPkg = generateVerificationPackage(
        kit,
        activeContract,
        data.solidityCode,
        data.robinhoodContractAddress ? 'robinhood-mainnet' : 'base-mainnet',
      )
      verFolder.file('standard-json-input.json', verPkg.standardJsonInput)
      verFolder.file(
        'verify_commands.sh',
        `#!/bin/bash\n# Verification script for ${kit.tokenName}\n${verPkg.foundryVerifyCommand}\n\n# Hardhat\n${verPkg.hardhatVerifyCommand}\n`,
      )
    }

    const solFolder = contractsFolder.folder('solana')
    if (solFolder) {
      solFolder.file(
        'create_spl_token.sh',
        `#!/bin/bash
# Solana SPL Token Creation for ${kit.tokenName} (${symbol})
echo "Creating SPL Token..."
spl-token create-token --decimals 9
echo "Minting supply: ${kit.tokenomics.supply}"
spl-token mint <MINT_ADDRESS> ${kit.tokenomics.supply.replace(/,/g, '')}
spl-token authorize <MINT_ADDRESS> mint --disable
echo "Mint authority disabled. Immature supply locked."
`,
      )
    }
  }

  // 5. Telegram Bot Folder
  const botFolder = zip.folder('bot')
  if (botFolder) {
    botFolder.file(
      'bot.js',
      `// Telegram Community Bot for ${kit.tokenName}
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
if (!BOT_TOKEN) { console.error("TELEGRAM_BOT_TOKEN is required"); process.exit(1); }
console.log("Starting ${kit.tokenName} Community Bot...");
`,
    )
    botFolder.file(
      'package.json',
      JSON.stringify(
        {
          name: `${cleanSymbol}-telegram-bot`,
          version: '1.0.0',
          scripts: { start: 'node bot.js' },
        },
        null,
        2,
      ),
    )
    botFolder.file(
      'README.md',
      `# ${kit.tokenName} Telegram Bot\nSet TELEGRAM_BOT_TOKEN and run \`npm start\`.`,
    )
  }

  // 6. Exchanges & Liquidity
  const exFolder = zip.folder('exchanges')
  if (exFolder) {
    exFolder.file(
      'robinhood_readiness.md',
      `# Robinhood Listing Readiness Blueprint: ${kit.tokenName}

### Retail Criteria
- **Tax:** 0% / 0% (Clean order book compatibility)
- **Supply:** ${kit.tokenomics.supply}
- **Liquidity Lock:** Minimum 12 months on UNCX or Raydium
- **Robinhood Connect:** Direct fiat onramp integration enabled
`,
    )

    exFolder.file(
      'liquidity_guide.md',
      `# DEX Liquidity Seeding Guide

### 1. Base / Ethereum (Uniswap V3 & Aerodrome)
- Supply 85% of total supply (${kit.tokenomics.supply}) paired with ETH.
- Set fee tier to 0.30% or 1.00%.
- Lock LP tokens using UNCX Network or Team Finance.

### 2. Solana (Raydium)
- Create Raydium CPMM Pool with SOL pairing.
- Revoke mint authority before adding liquidity.
`,
    )

    const listingsFolder = exFolder.folder('listings')
    if (listingsFolder) {
      const listingPkg = generateListingPackage(
        kit,
        activeContract,
        data.robinhoodContractAddress ? 'Robinhood Chain Mainnet (42170)' : 'Base Mainnet',
      )
      listingsFolder.file('dexscreener.json', listingPkg.dexScreenerJson)
      listingsFolder.file('coingecko_application.md', listingPkg.coinGeckoMarkdown)
      listingsFolder.file('coinmarketcap_application.md', listingPkg.coinMarketCapMarkdown)
    }
  }

  return zip.generateAsync({ type: 'blob' })
}

export function downloadBlobAsFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
